---
services:
  db0:
    image:
      ${POSTGRES_IMAGE:-postgres:${POSTGRES_VERSION:-16}}
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      -c wal_level=logical
      -c ssl=${POSTGRES_SSL:-on}
      -c ssl_cert_file=${POSTGRES_SSL_CERT_FILE:-/etc/ssl/certs/ssl-cert-snakeoil.pem}
      -c ssl_key_file=${POSTGRES_SSL_KEY_FILE:-/etc/ssl/private/ssl-cert-snakeoil.key}
    ports:
      - 5432:5432
    volumes:
      - db0:/var/lib/postgresql/data
      - type: bind
        source: example/initdb.d/
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: example/data
        target: /mnt
    pull_policy:
      ${PULL_POLICY:-missing}
volumes:
  db0:
    driver: local
