---
services:
  db0:
    image:
      ${POSTGRES_IMAGE:-postgres:${POSTGRES_VERSION:-15}}
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      -c wal_level=logical
    ports:
      - 5432:5432
    volumes:
      - db0:/var/lib/postgresql/data
      - type: bind
        source: example/initdb.d/
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: example/data
        target: /mnt
    pull_policy:
      ${PULL_POLICY:-missing}
volumes:
  db0:
    driver: local
