---
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25, 26]
        postgres: ['14', '15', '16beta1']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: make all dialyze eunit
      - run: docker-compose --project-directory etc/github-ci up --detach
        env:
          POSTGRES_VERSION: ${{matrix.postgres}}
      - name: Common Test
        run: make ct
        env:
          PGMP_PGMP_REPLICATION_ENABLED: false
          PGMP_DATABASE_USER: ci
          PGMP_DATABASE_NAME: postgres
          PGMP_DATABASE_PASSWORD: ci
      - uses: actions/upload-artifact@v3
        with:
          name: ct-logs
          path: logs
