---
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['25', '26']
        postgres: ['14', '15', '16beta1']
    steps:
      - uses: actions/checkout@v3
      - run: >-
          docker-compose
          --file etc/github-ci/compose.yaml
          --project-directory etc/github-ci
          up
          --detach
        env:
          POSTGRES_VERSION: ${{matrix.postgres}}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: make all dialyze eunit
      - run: make ct
        env:
          PGMP_PGMP_REPLICATION_ENABLED: false
          PGMP_DATABASE_USER: postgres
          PGMP_DATABASE_NAME: postgres
          PGMP_DATABASE_PASSWORD: postgres
      - uses: actions/upload-artifact@v3
        with:
          name: ct-logs-otp-${{matrix.otp}}-pg-${{matrix.postgres}}
          path: logs
