---
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1
      - name: Build
        run: make deps app dialyze eunit
      - name: PostgreSQL wal_level = logical
        run: |
          sudo pg_conftool set wal_level logical
      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create PostgreSQL ci user
        run: |
          sudo -u postgres psql --command="create user ci password 'ci' superuser replication"
      - name: Common Test
        run: make ct
        env:
          PGMP_PGMP_REPLICATION_ENABLED: false
          PGMP_DATABASE_USER: ci
          PGMP_DATABASE_NAME: postgres
          PGMP_DATABASE_PASSWORD: ci
      - uses: actions/upload-artifact@v3
        with:
          name: ct-logs
          path: logs
